### ISSUE TITLE
Legacy Roadmap

### ISSUE THREAD

**Issue by alkaitagi** [alkaitagi/avzag_flutter#50]
### Navigation

- [ ] Fix initial Aghul
- [ ] Rethink routes

### Enhancements

- [ ] Refactor Store
- [ ] Refactor Home
- [ ] Refactor Dictionary
- [ ] Serialization builder (& auto-nulling) w\ **Freezed**

### UI

- [ ] Group terms for single entry w\ **Collection**
- [ ] Better term de-grouping based on tags w\ **Collection**
- [ ] Tags editing suggestions (closes #30)
- [ ] Warning on existing headword

### Features

- [ ] Daily word notification
- [ ] API for words (json & md)
